### ISSUE TITLE
Not sure how to set up.

### ISSUE THREAD

**Issue by Ghostviper1907** [gumbobr0t/Hazard-Token-Grabber-v2#22]
Hi, sorry that it is probably a dumb question as I am new to using hazard v2 and github but it says "Extract to ZIP to your Desktop and enter the Hazard-Token-Grabber-v2 folder. In there, just run start.bat and follow the instructions that it gives to you." where exactly do I enter the Hazard-Token-Grabber-v2 folder as it just says "In there" I tried putting it in cmd, python but nothing worked, I also tried opening the start.bat folder but something flashed on my screen then closed instantly, I believe thats the thing for the victim but I am unsure. Any help would be greatly appriciated.

**Comment by Ghostviper1907** [comment]
I now realise that it means to go into the folder but now I am facing another problem, "just run start.bat" whenever I do this I think it is cmd that opens but it then closes instantly, I tried running as administrator but it did the same, am I doing something wrong?

**Comment by gumbobr0t** [comment]
Probably python not added to path, i'd just recommend you to use [Rose-grabber](https://github.com/DamagingRose/Rose-Grabber). It got & ui builder & way more features than hazard. I think it should work for you then.
